Updated to CheckStyle 8.25
Skatteetaten/checkstyle-config pull request #6
Opened 2019-10-09 12:08 UTC by stenaksel

Det er ingen andre endringer enn å få siste CheckStyle til å kjøre.

2019-10-10 12:51 UTC, Aerlant commented
Kan du formattere den så kun endringene vises i changed? (Så evt. lage en egen PR på formatteringsendring)

2019-10-16 07:21 UTC, bjartek commented
Denne er bygget og lagt opp til sonatype-snapshot med versjonen PR_6-SNAPSHOT. Når jeg bruker den i kombinasjon med 8.25 får jeg følgende feil
`Failed during checkstyle configuration: cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard. -> [Help 1]`

2019-10-16 07:21 UTC, bjartek requested changes
Denne er bygget og lagt opp til sonatype-snapshot med versjonen PR_6-SNAPSHOT. Når jeg bruker den i kombinasjon med 8.25 får jeg følgende feil
`Failed during checkstyle configuration: cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard. -> [Help 1]`

2019-10-17 05:56 UTC, Aerlant commented
Hvis du ser på files changed så er det mange formatteringsendringer som gjør det vanskelig å se hva som faktisk er gjort.

2019-10-17 07:33 UTC, bjartek commented
> Hvis du ser på files changed så er det mange formatteringsendringer som gjør det vanskelig å se hva som faktisk er gjort.

Du kan la være å vise whitespace changes i pr dialogen, da er det litt lettere å se endringene.

2019-10-30 08:13 UTC, stenaksel commented
> Hvis du ser på files changed så er det mange formatteringsendringer som gjør det vanskelig å se hva som faktisk er gjort.

Hvilken formatering skal benyttes? (Jeg benyttet Aurora)

2019-10-30 08:19 UTC, Aerlant commented
> > Hvis du ser på files changed så er det mange formatteringsendringer som gjør det vanskelig å se hva som faktisk er gjort.
> 
> Hvilken formatering skal benyttes? (Jeg benyttet Aurora)

Se Bjarte sitt svar, jeg som er noob :)

2019-10-30 08:43 UTC, stenaksel commented
> Denne er bygget og lagt opp til sonatype-snapshot med versjonen PR_6-SNAPSHOT. Når jeg bruker den i kombinasjon med 8.25 får jeg følgende feil
> `Failed during checkstyle configuration: cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard. -> [Help 1]`

Jeg forsto ikke helt denne Bjarte. Kan vi ta en prat (felleskoding)?

2019-10-31 08:46 UTC, merged